
2019-12-11 15:42:28,179:ERROR:main:ZeroDivisonError
Traceback (most recent call last):
  File "2_advance_logging.py", line 24, in devide
    result = x / y
ZeroDivisionError: division by zero
2019-12-11 15:42:28,179:INFO:main:add : 10 + 0 = 10
2019-12-11 15:42:28,180:INFO:main:add : 10 + 0 = 10
