2019-06-13 16:59:37,815:ERROR:main:ZeroDivisonError
Traceback (most recent call last):
  File "advance_stdout_logging.py", line 24, in devide
    result = x / y
ZeroDivisionError: division by zero
2019-06-13 17:01:10,255:ERROR:main:ZeroDivisonError
Traceback (most recent call last):
  File "advance_stdout_logging.py", line 24, in devide
    result = x / y
ZeroDivisionError: division by zero
